export const types = {
    START_FETCHING:      "START_FETCHING",
    STOP_FETCHING:       "STOP_FETCHING",
    EMIT_ERROR:          "EMIT_ERROR",
    INPUT_TASK:          "INPUT_TASK",
    CLEAR_TASK:          "CLEAR_TASK",
    CHECK_ALL_TASKS:     "CHECK_ALL_TASKS",
    START_EDITING_TASK:  "START_EDITING_TASK",
    FINISH_EDITING_TASK: "FINISH_EDITING_TASK",
    CURRENT_INPUT:       "CURRENT_INPUT",
    NEW_MESSAGE_TASK:    "NEW_MESSAGE_TASK",
    PREV_MESSAGE:        'PREV_MESSAGE',
};
