export const types = {
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING:  'STOP_FETCHING',
    EMIT_ERROR:     'EMIT_ERROR',
    INPUT_TASK:     'INPUT_TASK',
    CLEAR_TASK:     'CLEAR_TASK',

};
